// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Hello.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hello struct {
	DeMedVersion         string           `protobuf:"bytes,1,opt,name=DeMedVersion,proto3" json:"DeMedVersion,omitempty"`
	Ip                   []byte           `protobuf:"bytes,2,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port                 uint32           `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	PubKey               *Hello_PublicKey `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c7d5951a24764e, []int{0}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetDeMedVersion() string {
	if m != nil {
		return m.DeMedVersion
	}
	return ""
}

func (m *Hello) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *Hello) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Hello) GetPubKey() *Hello_PublicKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type Hello_PublicKey struct {
	N                    []byte   `protobuf:"bytes,1,opt,name=N,proto3" json:"N,omitempty"`
	E                    int32    `protobuf:"varint,2,opt,name=E,proto3" json:"E,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello_PublicKey) Reset()         { *m = Hello_PublicKey{} }
func (m *Hello_PublicKey) String() string { return proto.CompactTextString(m) }
func (*Hello_PublicKey) ProtoMessage()    {}
func (*Hello_PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c7d5951a24764e, []int{0, 0}
}

func (m *Hello_PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello_PublicKey.Unmarshal(m, b)
}
func (m *Hello_PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello_PublicKey.Marshal(b, m, deterministic)
}
func (m *Hello_PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello_PublicKey.Merge(m, src)
}
func (m *Hello_PublicKey) XXX_Size() int {
	return xxx_messageInfo_Hello_PublicKey.Size(m)
}
func (m *Hello_PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_Hello_PublicKey proto.InternalMessageInfo

func (m *Hello_PublicKey) GetN() []byte {
	if m != nil {
		return m.N
	}
	return nil
}

func (m *Hello_PublicKey) GetE() int32 {
	if m != nil {
		return m.E
	}
	return 0
}

func init() {
	proto.RegisterType((*Hello)(nil), "DeMed.Hello")
	proto.RegisterType((*Hello_PublicKey)(nil), "DeMed.Hello.PublicKey")
}

func init() {
	proto.RegisterFile("Hello.proto", fileDescriptor_13c7d5951a24764e)
}

var fileDescriptor_13c7d5951a24764e = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf6, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x75, 0x49, 0xf5, 0x4d, 0x4d, 0x51, 0x5a,
	0xc1, 0xc8, 0xc5, 0x0a, 0x16, 0x16, 0x52, 0xe2, 0xe2, 0x01, 0x0b, 0x85, 0xa5, 0x16, 0x15, 0x67,
	0xe6, 0xe7, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xa1, 0x88, 0x09, 0xf1, 0x71, 0x31, 0x79,
	0x16, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0x31, 0x79, 0x16, 0x08, 0x09, 0x71, 0xb1, 0x04,
	0xe4, 0x17, 0x95, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x06, 0x81, 0xd9, 0x42, 0x7a, 0x5c, 0x6c,
	0x01, 0xa5, 0x49, 0xde, 0xa9, 0x95, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x62, 0x7a, 0x60,
	0x23, 0xf4, 0x20, 0x96, 0x07, 0x94, 0x26, 0xe5, 0x64, 0x26, 0x7b, 0xa7, 0x56, 0x06, 0x41, 0x55,
	0x49, 0xa9, 0x73, 0x71, 0xc2, 0x05, 0x85, 0x78, 0xb8, 0x18, 0xfd, 0xc0, 0x36, 0xf3, 0x04, 0x31,
	0xfa, 0x81, 0x78, 0xae, 0x60, 0xdb, 0x58, 0x83, 0x18, 0x5d, 0x9d, 0xb8, 0xa2, 0x38, 0xc0, 0x4e,
	0x4f, 0x2a, 0x4d, 0x4b, 0x62, 0x03, 0xb3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xf6,
	0xde, 0x80, 0xd3, 0x00, 0x00, 0x00,
}
