// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MedicineOffer.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MedicineOffer struct {
	Meds                 []*MedicineOffer_Medicine `protobuf:"bytes,1,rep,name=meds,proto3" json:"meds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MedicineOffer) Reset()         { *m = MedicineOffer{} }
func (m *MedicineOffer) String() string { return proto.CompactTextString(m) }
func (*MedicineOffer) ProtoMessage()    {}
func (*MedicineOffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30e132fb543c60a, []int{0}
}

func (m *MedicineOffer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedicineOffer.Unmarshal(m, b)
}
func (m *MedicineOffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedicineOffer.Marshal(b, m, deterministic)
}
func (m *MedicineOffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedicineOffer.Merge(m, src)
}
func (m *MedicineOffer) XXX_Size() int {
	return xxx_messageInfo_MedicineOffer.Size(m)
}
func (m *MedicineOffer) XXX_DiscardUnknown() {
	xxx_messageInfo_MedicineOffer.DiscardUnknown(m)
}

var xxx_messageInfo_MedicineOffer proto.InternalMessageInfo

func (m *MedicineOffer) GetMeds() []*MedicineOffer_Medicine {
	if m != nil {
		return m.Meds
	}
	return nil
}

type MedicineOffer_Medicine struct {
	UUID                 string               `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Amount               int32                `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	PZN                  int64                `protobuf:"varint,6,opt,name=PZN,proto3" json:"PZN,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MedicineOffer_Medicine) Reset()         { *m = MedicineOffer_Medicine{} }
func (m *MedicineOffer_Medicine) String() string { return proto.CompactTextString(m) }
func (*MedicineOffer_Medicine) ProtoMessage()    {}
func (*MedicineOffer_Medicine) Descriptor() ([]byte, []int) {
	return fileDescriptor_e30e132fb543c60a, []int{0, 0}
}

func (m *MedicineOffer_Medicine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedicineOffer_Medicine.Unmarshal(m, b)
}
func (m *MedicineOffer_Medicine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedicineOffer_Medicine.Marshal(b, m, deterministic)
}
func (m *MedicineOffer_Medicine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedicineOffer_Medicine.Merge(m, src)
}
func (m *MedicineOffer_Medicine) XXX_Size() int {
	return xxx_messageInfo_MedicineOffer_Medicine.Size(m)
}
func (m *MedicineOffer_Medicine) XXX_DiscardUnknown() {
	xxx_messageInfo_MedicineOffer_Medicine.DiscardUnknown(m)
}

var xxx_messageInfo_MedicineOffer_Medicine proto.InternalMessageInfo

func (m *MedicineOffer_Medicine) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *MedicineOffer_Medicine) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MedicineOffer_Medicine) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MedicineOffer_Medicine) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MedicineOffer_Medicine) GetPZN() int64 {
	if m != nil {
		return m.PZN
	}
	return 0
}

func (m *MedicineOffer_Medicine) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*MedicineOffer)(nil), "DeMed.MedicineOffer")
	proto.RegisterType((*MedicineOffer_Medicine)(nil), "DeMed.MedicineOffer.Medicine")
}

func init() {
	proto.RegisterFile("MedicineOffer.proto", fileDescriptor_e30e132fb543c60a)
}

var fileDescriptor_e30e132fb543c60a = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0xc7, 0x89, 0x7d, 0x71, 0x3e, 0x45, 0x90, 0x47, 0x91, 0x50, 0x10, 0x83, 0xa7, 0x9c, 0x32,
	0x9c, 0x9f, 0x40, 0xe9, 0xc5, 0xc3, 0x54, 0xc2, 0x76, 0xd9, 0xcd, 0xad, 0x4f, 0x47, 0x60, 0x69,
	0x4a, 0x9b, 0x7d, 0x2f, 0xbf, 0x9c, 0x77, 0x59, 0x6a, 0x60, 0xbd, 0xfd, 0xdf, 0x92, 0x87, 0x1f,
	0xdc, 0x2e, 0xa9, 0x36, 0x3b, 0xd3, 0xd2, 0x67, 0xd3, 0x50, 0xaf, 0xba, 0xde, 0x79, 0x87, 0x59,
	0x45, 0x4b, 0xaa, 0xcb, 0xc7, 0xbd, 0x73, 0xfb, 0x03, 0xcd, 0x43, 0xb8, 0x3d, 0x36, 0x73, 0x6f,
	0x2c, 0x0d, 0xfe, 0xdb, 0x76, 0xe3, 0xee, 0xe9, 0x97, 0xc1, 0xf5, 0xe4, 0x3d, 0x3e, 0x43, 0x6a,
	0xa9, 0x1e, 0x38, 0x13, 0x89, 0x2c, 0x16, 0x0f, 0x2a, 0x7c, 0xa4, 0xa6, 0x37, 0xa2, 0xd3, 0x61,
	0x5a, 0xfe, 0x30, 0x98, 0xc5, 0x08, 0x11, 0xd2, 0xf5, 0xfa, 0xbd, 0xe2, 0x4c, 0x30, 0x79, 0xa5,
	0x83, 0xc6, 0x3b, 0xc8, 0x56, 0xc6, 0x1f, 0x88, 0x5f, 0x84, 0x70, 0x34, 0x28, 0xa0, 0xa8, 0x68,
	0xd8, 0xf5, 0xa6, 0xf3, 0xc6, 0xb5, 0x3c, 0x09, 0xdd, 0x79, 0x84, 0xf7, 0x90, 0xbf, 0x5a, 0x77,
	0x6c, 0x3d, 0xcf, 0x04, 0x93, 0x99, 0xfe, 0x77, 0x78, 0x03, 0xc9, 0xd7, 0xe6, 0x83, 0xe7, 0x82,
	0xc9, 0x44, 0x9f, 0x24, 0x2a, 0x48, 0x4f, 0x68, 0xfc, 0x52, 0x30, 0x59, 0x2c, 0x4a, 0x35, 0x72,
	0xab, 0xc8, 0xad, 0x56, 0x91, 0x5b, 0x87, 0xdd, 0x1b, 0x6c, 0x66, 0xb1, 0xdb, 0xe6, 0x41, 0xbd,
	0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x25, 0xec, 0x76, 0x59, 0x49, 0x01, 0x00, 0x00,
}
