// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MessageBroadcast.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageBroadcast struct {
	Origin               []byte   `protobuf:"bytes,1,opt,name=Origin,proto3" json:"Origin,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	Subject              string   `protobuf:"bytes,4,opt,name=Subject,proto3" json:"Subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageBroadcast) Reset()         { *m = MessageBroadcast{} }
func (m *MessageBroadcast) String() string { return proto.CompactTextString(m) }
func (*MessageBroadcast) ProtoMessage()    {}
func (*MessageBroadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d644348af0e3215, []int{0}
}

func (m *MessageBroadcast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBroadcast.Unmarshal(m, b)
}
func (m *MessageBroadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBroadcast.Marshal(b, m, deterministic)
}
func (m *MessageBroadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBroadcast.Merge(m, src)
}
func (m *MessageBroadcast) XXX_Size() int {
	return xxx_messageInfo_MessageBroadcast.Size(m)
}
func (m *MessageBroadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBroadcast.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBroadcast proto.InternalMessageInfo

func (m *MessageBroadcast) GetOrigin() []byte {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *MessageBroadcast) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *MessageBroadcast) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageBroadcast) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageBroadcast)(nil), "DeMed.MessageBroadcast")
}

func init() {
	proto.RegisterFile("MessageBroadcast.proto", fileDescriptor_1d644348af0e3215)
}

var fileDescriptor_1d644348af0e3215 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf3, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x75, 0x2a, 0xca, 0x4f, 0x4c, 0x49, 0x4e, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x75, 0x49, 0xf5, 0x4d, 0x4d, 0x51, 0xca, 0xe1, 0x12, 0x40, 0x57, 0x20,
	0x24, 0xc6, 0xc5, 0xe6, 0x5f, 0x94, 0x99, 0x9e, 0x99, 0x27, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13,
	0x04, 0xe5, 0x09, 0x09, 0x71, 0xb1, 0x78, 0x24, 0x16, 0x67, 0x48, 0x30, 0x81, 0x45, 0xc1, 0x6c,
	0x90, 0x58, 0x48, 0x6a, 0x45, 0x89, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x24,
	0xc1, 0xc5, 0x1e, 0x5c, 0x9a, 0x94, 0x95, 0x9a, 0x5c, 0x22, 0xc1, 0x02, 0x16, 0x86, 0x71, 0x9d,
	0xb8, 0xa2, 0x38, 0xc0, 0xb6, 0x27, 0x95, 0xa6, 0x25, 0xb1, 0x81, 0x59, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x40, 0xeb, 0x54, 0xf7, 0xa1, 0x00, 0x00, 0x00,
}
