// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MessageFrame.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageFrame struct {
	PayloadType          uint32               `protobuf:"varint,1,opt,name=payloadType,proto3" json:"payloadType,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Payload              []byte               `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MessageFrame) Reset()         { *m = MessageFrame{} }
func (m *MessageFrame) String() string { return proto.CompactTextString(m) }
func (*MessageFrame) ProtoMessage()    {}
func (*MessageFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb26dd00487d00fd, []int{0}
}

func (m *MessageFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageFrame.Unmarshal(m, b)
}
func (m *MessageFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageFrame.Marshal(b, m, deterministic)
}
func (m *MessageFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageFrame.Merge(m, src)
}
func (m *MessageFrame) XXX_Size() int {
	return xxx_messageInfo_MessageFrame.Size(m)
}
func (m *MessageFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageFrame.DiscardUnknown(m)
}

var xxx_messageInfo_MessageFrame proto.InternalMessageInfo

func (m *MessageFrame) GetPayloadType() uint32 {
	if m != nil {
		return m.PayloadType
	}
	return 0
}

func (m *MessageFrame) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *MessageFrame) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageFrame)(nil), "DeMed.MessageFrame")
}

func init() {
	proto.RegisterFile("MessageFrame.proto", fileDescriptor_cb26dd00487d00fd)
}

var fileDescriptor_cb26dd00487d00fd = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf2, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x75, 0x2b, 0x4a, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x75, 0x49, 0xf5, 0x4d, 0x4d, 0x91, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b,
	0x26, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0xd4, 0x29,
	0x55, 0x71, 0xf1, 0x20, 0xeb, 0x16, 0x52, 0xe0, 0xe2, 0x2e, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c,
	0x09, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d, 0x42, 0x16, 0x12, 0xd2, 0xe3,
	0x62, 0x01, 0x19, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa5, 0x07, 0xb1, 0x41, 0x0f,
	0x66, 0x83, 0x5e, 0x08, 0xcc, 0x86, 0x20, 0xb0, 0x3a, 0x21, 0x09, 0x2e, 0x76, 0xa8, 0x76, 0x09,
	0x66, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0xd7, 0x89, 0x2b, 0x8a, 0x03, 0xa6, 0x2b, 0x89, 0x0d,
	0xcc, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x6a, 0x14, 0x00, 0xcc, 0x00, 0x00, 0x00,
}
