// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RequestBroadcast.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestBroadcast struct {
	Origin               []byte   `protobuf:"bytes,1,opt,name=Origin,proto3" json:"Origin,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	PZN                  string   `protobuf:"bytes,4,opt,name=PZN,proto3" json:"PZN,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Quantity             uint32   `protobuf:"varint,6,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestBroadcast) Reset()         { *m = RequestBroadcast{} }
func (m *RequestBroadcast) String() string { return proto.CompactTextString(m) }
func (*RequestBroadcast) ProtoMessage()    {}
func (*RequestBroadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbf10636fc86f07e, []int{0}
}

func (m *RequestBroadcast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestBroadcast.Unmarshal(m, b)
}
func (m *RequestBroadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestBroadcast.Marshal(b, m, deterministic)
}
func (m *RequestBroadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestBroadcast.Merge(m, src)
}
func (m *RequestBroadcast) XXX_Size() int {
	return xxx_messageInfo_RequestBroadcast.Size(m)
}
func (m *RequestBroadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestBroadcast.DiscardUnknown(m)
}

var xxx_messageInfo_RequestBroadcast proto.InternalMessageInfo

func (m *RequestBroadcast) GetOrigin() []byte {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *RequestBroadcast) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RequestBroadcast) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *RequestBroadcast) GetPZN() string {
	if m != nil {
		return m.PZN
	}
	return ""
}

func (m *RequestBroadcast) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestBroadcast) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestBroadcast)(nil), "DeMed.RequestBroadcast")
}

func init() {
	proto.RegisterFile("RequestBroadcast.proto", fileDescriptor_bbf10636fc86f07e)
}

var fileDescriptor_bbf10636fc86f07e = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0b, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x71, 0x2a, 0xca, 0x4f, 0x4c, 0x49, 0x4e, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x75, 0x49, 0xf5, 0x4d, 0x4d, 0x51, 0x9a, 0xc2, 0xc8, 0x25, 0x80, 0xae,
	0x42, 0x48, 0x8c, 0x8b, 0xcd, 0xbf, 0x28, 0x33, 0x3d, 0x33, 0x4f, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x27, 0x08, 0xca, 0x13, 0x12, 0xe2, 0x62, 0xf1, 0x48, 0x2c, 0xce, 0x90, 0x60, 0x02, 0x8b, 0x82,
	0xd9, 0x20, 0xb1, 0x90, 0xd4, 0x8a, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b,
	0x48, 0x80, 0x8b, 0x39, 0x20, 0xca, 0x4f, 0x82, 0x05, 0x2c, 0x04, 0x62, 0x82, 0x54, 0xf9, 0x25,
	0xe6, 0xa6, 0x4a, 0xb0, 0x42, 0x54, 0x81, 0xd8, 0x42, 0x52, 0x5c, 0x1c, 0x81, 0xa5, 0x89, 0x79,
	0x25, 0x99, 0x25, 0x95, 0x12, 0x6c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x70, 0xbe, 0x13, 0x57, 0x14,
	0x07, 0xd8, 0x99, 0x49, 0xa5, 0x69, 0x49, 0x6c, 0x60, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x74, 0x8e, 0xe2, 0xeb, 0xca, 0x00, 0x00, 0x00,
}
